name: ci 
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: cd docs
      - run: pip install pipenv
      - run: pipenv install 
      - run: pipenv run mkdocs gh-deploy --force
